WIFI_SSID = "Wokwi-GUEST"
WIFI_PASSWORD = ""

API_BASE_URL = "https://seu-backend.vercel.app"
ENDPOINT_LEITURAS = API_BASE_URL + "/leituras"

API_KEY = "troque_esta_chave_pelo_valor_real_do_supabase"

INTERVALO_AMOSTRA_SEGUNDOS = 10
AMOSTRAS_POR_ENVIO = 6

TEMP_VALIDA_MIN = -40.0
TEMP_VALIDA_MAX = 80.0
UMID_VALIDA_MIN = 0.0
UMID_VALIDA_MAX = 100.0

PINO_DHT22 = 4
TIMEOUT_HTTP_SEGUNDOS = 10
MAX_TENTATIVAS = 3
